### ISSUE TITLE
Native NeoForge support

### ISSUE THREAD

**Issue by AsheX1** [ps-dps/MobCaptains#30]
using https://modrinth.com/datapack/mob-captains/version/v3.1.1+mod

i get mobcaptains-v3.1.1.jar is a fabric mod and cannet be loaded

im using neoforge is there any config file in the jar to make it load anyways

**Comment by PuckiSilver** [comment]
Neoforge is explicitly not listed as a viable mod loader, only Forge, Fabric and Quilt.

Did you try it using one of those?
In what way does it break? Does it just not show up/load or does it show an error?

**Comment by AsheX1** [comment]
![image](https://github.com/ps-dps/MobCaptains/assets/6249407/5384b664-d269-4019-a43a-c942106ced5e)

this what the log says

[12Jan2024 16:08:23.830] [main/ERROR] [net.minecraftforge.fml.loading.moddiscovery.ModInfo/FATAL]: Invalid modId found in file C:\Users\Ashe\Desktop\Games\Prismmc\instances\1.20.1 modded\.minecraft\mods\MobCaptains-v3.1.1.jar - mob-captains does not match the standard: ^[a-z][a-z0-9_]{1,63}$
[12Jan2024 16:08:23.831] [main/ERROR] [net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Locator {mods folder locator at C:\Users\Ashe\Desktop\Games\Prismmc\instances\1.20.1 modded\.minecraft\mods} found an invalid mod file net.minecraftforge.fml.loading.moddiscovery.ModFileInfo@5cf8edcf
net.minecraftforge.fml.loading.moddiscovery.InvalidModFileException: Invalid modId found : mob-captains (MobCaptains-v3.1.1.jar)
	at net.minecraftforge.fml.loading.moddiscovery.ModInfo.<init>(ModInfo.java:62) ~[loader-47.1.47.jar:47.1]
	at net.minecraftforge.fml.loading.moddiscovery.ModFileInfo.lambda$new$2(ModFileInfo.java:85) ~[loader-47.1.47.jar:47.1]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
	at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModFileInfo.<init>(ModFileInfo.java:86) ~[loader-47.1.47.jar:47.1]
	at net.minecraftforge.fml.loading.moddiscovery.ModFileParser.modsTomlParser(ModFileParser.java:47) ~[loader-47.1.47.jar:47.1]
	at net.minecraftforge.fml.loading.moddiscovery.ModFileParser.readModList(ModFileParser.java:31) ~[loader-47.1.47.jar:47.1]
	at net.minecraftforge.fml.loading.moddiscovery.ModFile.<init>(ModFile.java:79) ~[loader-47.1.47.jar:47.1]
	at net.minecraftforge.fml.loading.moddiscovery.ModFile.<init>(ModFile.java:68) ~[loader-47.1.47.jar:47.1]
	at net.minecraftforge.fml.loading.moddiscovery.AbstractModProvider.createMod(AbstractModProvider.java:52) ~[loader-47.1.47.jar:47.1]
	at net.minecraftforge.fml.loading.moddiscovery.AbstractJarFileModLocator.lambda$scanMods$0(AbstractJarFileModLocator.java:21) ~[loader-47.1.47.jar:47.1]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
	at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395) ~[?:?]
	at java.util.stream.Sink$ChainedReference.end(Sink.java:261) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
	at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
	at net.minecraftforge.fml.loading.moddiscovery.AbstractJarFileModLocator.scanMods(AbstractJarFileModLocator.java:21) ~[loader-47.1.47.jar:47.1]
	at net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:75) ~[loader-47.1.47.jar:47.1]
	at net.minecraftforge.fml.loading.FMLLoader.beginModScan(FMLLoader.java:164) ~[loader-47.1.47.jar:47.1]
	at net.minecraftforge.fml.loading.FMLServiceProvider.beginScanning(FMLServiceProvider.java:86) ~[loader-47.1.47.jar:47.1]
	at cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:112) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:100) ~[modlauncher-10.0.9.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1787) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
	at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
	at cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:102) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:55) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:88) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) ~[?:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[?:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[?:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[?:?]

**Comment by PuckiSilver** [comment]
I see that it’s complaining about the mod id, I'll change that and re-upload, but I'm not sure if this is the actual reason this doesn’t work on neoforge.

If I can easily make it work for neoforge, I will also add that when I get the time.

Thanks for the report!

**Comment by PuckiSilver** [comment]
If I actually want to fully support it, I will read more into it, changing the modid though should be possible within the next days, maybe that fixes it for now

**Comment by PuckiSilver** [comment]
I changed the modid in this version I just released.
Can you try this one and see if it works for you?

https://modrinth.com/datapack/mob-captains/version/v3.1.2+mod

**Comment by AsheX1** [comment]
> I changed the modid in a version I just released. Can you try this newest one and see if it works for you?
> 
> https://modrinth.com/datapack/mob-captains/version/v3.2.1+mod

it loaded on 1.20.1 neoforge gone test in a world now

**Comment by AsheX1** [comment]
everything seems to work now 
Neoforge 47.1.85 minecraft 1.20.1

so now just need to see if it still works if i go up in minecraft versions and neoforge version

**Comment by AsheX1** [comment]
its seems to also be working on 1.20.4
neoforge 20.4.91-beta

im gone leave this open for you to close but as far as i can see its gone work on all versions now great.

thanks for making it compatibil with neoforge

**Comment by PuckiSilver** [comment]
Thanks for checking multiple versions! I'm glad it works now.
Since NeoForge seems to use the forge configuration file 1:1 right now, this support is as native as it gets.
I will add NeoForge as a compatible mod loader and close this issue!
🚀
